@startuml
skinparam Shadowing false

class Train {
    + step()
    - advance(act : action) 
    - wait(act : action) 
    - release(act : action)
    - final(act : action) 
}

class Track {
    + get_connected_stations()
}

class Station {
    + get_connected_tracks() 
}

class Schedule {
    + push_action(act : action) 
    + pop_action() : action 
} 

class Route {
    + get_next() : station 
    + continue_route() 
}

class Timetable {
    + generate_timetable()
} 

class Environment {
    + step()
    + is_finished()
}

class World {
    + setup_railway_system()
    + run()
}

Train "1" --> "0..1" Track : occupied_track
Station "1" --> "1..*" Track : connected_tracks
Route "1" --> "1..* [O]" Station: stations 
Timetable "{train_id}1..*" --> "1..*" Route : train_to_route_map
Timetable "{train_id}1..*" --> "1..*" Schedule : train_to_schedule_map
Train "{train_id}1" --> "1" Route : train_route_schedule
Train "{train_id}1" --> "1" Schedule : train_route_schedule
World "1" --> "1" Environment: env 
World "1" -> "1..*" Track: tracks 
World "1" -> "1..*" Station: stations 
World "1" -> "1..*" Train: trains 
Environment "1" -> "1..*" Train: trains 

@enduml